// lib/vocab/catalog-server.ts
// Server-only — reads the prebuilt vocab catalog from disk. The catalog
// itself is generated by `npm run build:catalog` (scripts/build-vocab-catalog.ts).
// Client components should consume the data via props, not by importing this.
import { promises as fs } from "fs";
import path from "path";
import type { VocabCatalogItem } from "./catalog-types";

const VOCAB_CATALOG = path.join(process.cwd(), "lib/data/vocab-catalog.json");

export async function loadVocabCatalog(): Promise<VocabCatalogItem[]> {
  try {
    const raw = await fs.readFile(VOCAB_CATALOG, "utf-8");
    return JSON.parse(raw) as VocabCatalogItem[];
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === "ENOENT") return [];
    throw err;
  }
}
